### ISSUE TITLE
Tweet handeling error 

### ISSUE THREAD

**Issue by 05tb** [met-office-lab/molab-rhino-api#12]
If a tweet is received **without** containing any plain text but contains the keyword hashtag, then it will not be registered. 

A tweet will only be registered if it contains plain text. 

The issue lies in app.js as this handles twitter filtering.

**Comment by 05tb** [comment]
Pull request #14 attempts and succeeds to fix this issue

**Comment by tpowellmeto** [comment]
well done! #goldstar
